Repository Part3-team20/Taskify, pull requests merged in 2024-04, with the labels that each got.

#18 approuter 변경
  src/app/layout.tsx
  src/app/page.module.scss
  src/app/page.tsx
  src/pages/_app.tsx
  src/pages/_document.tsx
  src/pages/api/hello.ts
  src/pages/index.tsx
  tsconfig.json
Labels: ♻️refactor

#20 Feat: Modal DropDown Box 컴포넌트 생성(#11)
  public/images/check.svg
  src/components/DropDown/ColumnsDropDown/ColumnsDropDown.module.scss
  src/components/DropDown/ColumnsDropDown/ColumnsDropDown.tsx
  src/components/DropDown/MemberDropDown/MemberDropDown.module.scss
  src/components/DropDown/MemberDropDown/MemberDropDown.tsx
Labels: ✨component

#21 feat: chip 컴포넌트 구현
  .eslintrc.json
  package-lock.json
  package.json
  public/images/add_btn.svg
  public/images/check_icon.svg
  src/components/common/chip/ColorChip.module.scss
  src/components/common/chip/ColorChip.tsx
  src/components/common/chip/LabelChip.module.scss
  src/components/common/chip/LabelChip.tsx
  src/components/common/chip/NumberChip.module.scss
  src/components/common/chip/NumberChip.tsx
  src/components/common/chip/PlusChip.module.scss
  src/components/common/chip/PlusChip.tsx
  src/styles/globals.scss
  src/styles/reset.scss
Labels: ✨component

#23 feat: modal, modalInput, profileImg
  package-lock.json
  package.json
  public/images/profile.svg
  src/app/page.tsx
  src/components/modal/Modal.module.scss
  src/components/modal/Modal.tsx
  src/components/modal/modalExample/ExampleModal.tsx
  src/components/modal/modalInput/ModalInput.module.scss
  src/components/modal/modalInput/ModalInput.tsx
  src/components/modal/modalInput/commentInput/CommentInput.module.scss
  src/components/modal/modalInput/commentInput/CommentInput.tsx
  src/components/modal/modalInput/deadlineInput/DeadlineInput.module.scss
  src/components/modal/modalInput/deadlineInput/DeadlineInput.tsx
  src/components/modal/modalInput/tagInput/TagInput.module.scss
  src/components/modal/modalInput/tagInput/TagInput.tsx
  src/components/modal/modalInput/titleInput/TitleInput.module.scss
  src/components/modal/modalInput/titleInput/TitleInput.tsx
  src/components/profile/Profile.module.scss
  src/components/profile/Profile.tsx
Labels: ✨component

#22 feat: button 컴포넌트 구현(#6)
  .eslintrc.json
  package-lock.json
  package.json
  public/images/add_fill_box.svg
  public/images/arrow_icon_disabled.svg
  public/images/crown_icon 3.svg
  public/images/crown_icon.svg
  src/components/button/AddButton/AddButton.module.scss
  src/components/button/AddButton/index.tsx
  src/components/button/BasicSubmitButton/BasicSubmitButton.module.scss
  src/components/button/BasicSubmitButton/index.tsx
  src/components/button/Button/Button.module.scss
  src/components/button/Button/index.tsx
  src/components/button/DashboardButton/DashboardButton.module.scss
  src/components/button/DashboardButton/index.tsx
  src/components/button/DeleteDashboardButton/DeleteDashboardButton.module.scss
  src/components/button/DeleteDashboardButton/index.tsx
  src/components/button/IconTextButton/IconTextButton.module.scss
  src/components/button/IconTextButton/index.tsx
  src/components/button/LoginSubmitButton/LoginSubmitButton.module.scss
  src/components/button/LoginSubmitButton/index.tsx
  src/components/button/PaginationButton/PaginationButton.module.scss
  src/components/button/PaginationButton/index.tsx
  src/components/button/modal/ModalButton/ModalButton.module.scss
  src/components/button/modal/ModalButton/index.tsx
  src/components/button/modal/ModalSubmitButton/ModalSubmitButton.module.scss
  src/components/button/modal/ModalSubmitButton/index.tsx
  src/styles/_color.scss
  src/styles/_mixins.scss
  src/styles/_reset.scss
  src/styles/_responsive-styles.scss
Labels: ✨component

#27 Fix: chip컴포넌트, 프로필 이미지 컴포넌트 수정
  .eslintrc.json
  src/components/common/chip/ColorChip.module.scss
  src/components/common/chip/ColorChip.tsx
  src/components/common/chip/LabelChip.module.scss
  src/components/common/chip/LabelChip.tsx
  src/components/common/chip/PlusChip.module.scss
  src/components/common/chip/PlusChip.tsx
  src/components/profile/Profile.tsx
Labels: 🐛fix, ✨component

#28 feat: 사이드바 컴포넌트 추가(#10)
  src/components/SideBar/SideBar.module.scss
  src/components/SideBar/SideBarListItem/SideBarListItem.module.scss
  src/components/SideBar/SideBarListItem/index.tsx
  src/components/SideBar/index.tsx
  src/components/button/PaginationButton/PaginationButton.module.scss
  src/components/button/PaginationButton/index.tsx
Labels: ✨component

#36 fix: 파일구조, Rem 수정
  package-lock.json
  src/components/SideBar/SideBar.module.scss
  src/components/SideBar/SideBarListItem/SideBarListItem.module.scss
  src/components/SideBar/SideBarListItem/index.tsx
  src/components/SideBar/index.tsx
  src/components/common/Button/AddButton/AddButton.module.scss
  src/components/common/Button/AddButton/index.tsx
  src/components/common/Button/BasicSubmitButton/BasicSubmitButton.module.scss
  src/components/common/Button/BasicSubmitButton/index.tsx
  src/components/common/Button/Button/Button.module.scss
  src/components/common/Button/Button/index.tsx
  src/components/common/Button/DashboardButton/DashboardButton.module.scss
  src/components/common/Button/DashboardButton/index.tsx
  src/components/common/Button/DeleteDashboardButton/DeleteDashboardButton.module.scss
  src/components/common/Button/DeleteDashboardButton/index.tsx
  src/components/common/Button/IconTextButton/IconTextButton.module.scss
  src/components/common/Button/IconTextButton/index.tsx
  src/components/common/Button/LoginSubmitButton/LoginSubmitButton.module.scss
  src/components/common/Button/LoginSubmitButton/index.tsx
  src/components/common/Button/PaginationButton/PaginationButton.module.scss
  src/components/common/Button/PaginationButton/index.tsx
  src/components/common/Profile/Profile.module.scss
  src/components/common/Profile/Profile.tsx
  src/components/common/chip/ColorChip.module.scss
  src/components/common/chip/ColorChip.tsx
  src/components/common/chip/LabelChip.module.scss
  src/components/common/chip/LabelChip.tsx
  src/components/common/chip/NumberChip.module.scss
  src/components/common/chip/NumberChip.tsx
  src/components/common/chip/PlusChip.module.scss
  src/components/common/chip/PlusChip.tsx
  src/components/modal/Modal.module.scss
  src/components/modal/Modal.tsx
  src/components/modal/ModalButton/Button/ModalButton.module.scss
  src/components/modal/ModalButton/Button/index.tsx
  src/components/modal/ModalButton/SubmitButton/ModalSubmitButton.module.scss
  src/components/modal/ModalButton/SubmitButton/index.tsx
  src/components/modal/ModalDropDown/ColumnsDropDown/ColumnsDropDown.module.scss
  src/components/modal/ModalDropDown/ColumnsDropDown/ColumnsDropDown.tsx
  src/components/modal/ModalDropDown/MemberDropDown/MemberDropDown.module.scss
  src/components/modal/ModalDropDown/MemberDropDown/MemberDropDown.tsx
  src/components/modal/modalExample/ExampleModal.tsx
  src/components/modal/modalInput/ModalInput.module.scss
  src/components/modal/modalInput/ModalInput.tsx
  src/components/modal/modalInput/commentInput/CommentInput.module.scss
  src/components/modal/modalInput/commentInput/CommentInput.tsx
  src/components/modal/modalInput/deadlineInput/DeadlineInput.module.scss
  src/components/modal/modalInput/deadlineInput/DeadlineInput.tsx
  src/components/modal/modalInput/titleInput/TitleInput.module.scss
  src/components/modal/modalInput/titleInput/TitleInput.tsx
Labels: 🐛fix, ✨component

#37 feature: 공통 레이아웃 생성 및 적용(#31)
  src/app/dashboard/[boardId]/edit/page.tsx
  src/app/dashboard/[boardId]/page.tsx
  src/app/mydashboard/page.tsx
  src/app/mypage/page.tsx
  src/components/SideBar/SideBar.module.scss
  src/components/modal/Modal.module.scss
  src/layouts/CommonLayout/CommonLayout.module.scss
  src/layouts/CommonLayout/index.tsx
  src/styles/_variables.scss
Labels: 📄pages

#38 Feature: 카드 컴포넌트
  public/images/ProfileImg.svg
  src/components/Card/Card.module.scss
  src/components/Card/Card.tsx
  src/components/Card/mock.json
  src/components/common/Profile/Profile.module.scss
  src/components/common/Profile/Profile.tsx
  src/components/common/chip/ColorChip.module.scss
Labels: ✨component

#39 Feature: Input 컴포넌트
  package.json
  src/components/common/input/Input.module.scss
  src/components/common/input/index.tsx
Labels: ✨component

#40 feature: header 컴포넌트
  src/components/common/Header/DashBoardHeader/DashBoardHeader.module.scss
  src/components/common/Header/DashBoardHeader/EachDashBoardHeade/EachDashBoardHeader.module.scss
  src/components/common/Header/DashBoardHeader/EachDashBoardHeade/index.tsx
  src/components/common/Header/DashBoardHeader/index.tsx
  src/components/common/Header/LandingPageHeader/LandingPageHeader.module.scss
  src/components/common/Header/LandingPageHeader/index.tsx
Labels: ✨component

#41 feature: file-input 컴포넌트
  src/app/page.tsx
  src/components/common/FileInput/FileInput.module.scss
  src/components/common/FileInput/index.tsx
Labels: ✨component

#42 feat: 회원가입&로그인(#8)
  public/images/fullLogo.svg
  public/images/mainLogo.svg
  src/app/login/Login.module.scss
  src/app/login/page.tsx
  src/app/signup/Signup.module.scss
  src/app/signup/page.tsx
  src/components/common/input/PasswordInput/PasswordInput.module.scss
  src/components/common/input/PasswordInput/index.tsx
  src/hooks/useFetchPost.ts
Labels: 📄pages

#47 feature: 마이페이지 초안
  src/app/mypage/MyPage.module.scss
  src/app/mypage/page.tsx
  src/components/common/Button/GoBackButton/GoBackButton.module.scss
  src/components/common/Button/GoBackButton/index.tsx
Labels: 📄pages

#51 fix: fetch hooks 수정
  src/app/login/page.tsx
  src/app/signup/page.tsx
  src/hooks/useFetchPost.ts
  src/hooks/useFetchToken.ts
  src/hooks/useFormattedDate.ts
Labels: 🐛fix, 🪝hook

#45 대시보드 수정 페이지
  .eslintrc.json
  public/images/arrowReverse_icon.svg
  src/app/dashboard/[boardId]/edit/BoardEdit.module.scss
  src/app/dashboard/[boardId]/edit/editComponents/DashboardChange.module.scss
  src/app/dashboard/[boardId]/edit/editComponents/DashboardChange.tsx
  src/app/dashboard/[boardId]/edit/editComponents/InviteStatus.module.scss
  src/app/dashboard/[boardId]/edit/editComponents/InviteStatus.tsx
  src/app/dashboard/[boardId]/edit/editComponents/MemberManagement.module.scss
  src/app/dashboard/[boardId]/edit/editComponents/MemberManagement.tsx
  src/app/dashboard/[boardId]/edit/editComponents/PreviousPageButton.module.scss
  src/app/dashboard/[boardId]/edit/editComponents/PreviousPageButton.tsx
  src/app/dashboard/[boardId]/edit/page.tsx
  src/components/SideBar/index.tsx
  src/components/common/Button/BasicSubmitButton/index.tsx
  src/components/common/Button/DeleteDashboardButton/index.tsx
  src/components/common/Button/PaginationButton/index.tsx
  src/components/modal/Modal.module.scss
  src/components/modal/modalInput/tagInput/TagInput.tsx
  src/components/modal/modalInvite/ModalInvite.module.scss
  src/components/modal/modalInvite/ModalInvite.tsx
  src/layouts/CommonLayout/index.tsx
Labels: 📄pages

#50 feature: mydashboard 페이지, 대시보드 추가 모달 초안
  src/app/mydashboard/MyDashboard.module.scss
  src/app/mydashboard/page.tsx
  src/components/InvitedBoard/InviteList/index.tsx
  src/components/InvitedBoard/InviteList/inviteList.module.scss
  src/components/InvitedBoard/InviteListItem/InviteListItem.module.scss
  src/components/InvitedBoard/InviteListItem/index.tsx
  src/components/InvitedBoard/InvitedBoard.module.scss
  src/components/InvitedBoard/InvitedBoardSearchForm/InvitedBoardSearchForm.module.scss
  src/components/InvitedBoard/InvitedBoardSearchForm/index.tsx
  src/components/InvitedBoard/index.tsx
  src/components/InvitedBoard/mockData.ts
  src/components/MyDashboardList/MyDashboardList.module.scss
  src/components/MyDashboardList/index.tsx
  src/components/common/Button/AddButton/AddButton.module.scss
  src/components/common/Button/AddButton/index.tsx
  src/components/common/Button/Button/index.tsx
  src/components/common/Button/DashboardButton/DashboardButton.module.scss
  src/components/common/Button/DashboardButton/index.tsx
  src/components/modal/CreateDashboard/CreateDashboard.module.scss
  src/components/modal/CreateDashboard/index.tsx
  src/components/modal/modalInput/ModalInput.module.scss
  src/contexts/inviteContext.tsx
Labels: ✨component, 📄pages

#55 localstorage 토큰 저장 및 로그인 시 리다이렉트
  src/app/login/page.tsx
  src/app/signup/page.tsx
Labels: 🪝hook

#48 개별 대시보드 페이지
  .eslintrc.json
  src/app/dashboard/[boardId]/Dashboard.module.scss
  src/app/dashboard/[boardId]/page.tsx
  src/components/Column/Column.module.scss
  src/components/Column/index.tsx
  src/components/Column/mock.json
  src/components/common/chip/LabelChip.tsx
  src/components/modal/DeleteTask/index.tsx
Labels: ✨component, 📄pages

#53 feature: ModalPortal 적용(#52)
  src/app/layout.tsx
  src/components/MyDashboardList/index.tsx
  src/components/modal/ModalPortal.tsx
Labels: ♻️refactor

#58 feature: invite board 데이터 연결(#32)
  src/components/Card/Card.tsx
  src/components/Column/index.tsx
  src/components/InvitedBoard/mockData.ts
  src/components/MyDashboardList/index.tsx
  src/components/SideBar/index.tsx
  src/components/common/Button/GoBackButton/index.tsx
  src/components/common/FileInput/index.tsx
  src/components/modal/Task/Comment/Comments.tsx
  src/components/modal/Task/index.tsx
  src/components/modal/modalInput/tagInput/TagInput.tsx
  src/contexts/inviteContext.tsx
Labels: 📄pages

#59 feature: dashboard list 데이터 연결(#32, #10)
  src/components/MyDashboardList/index.tsx
  src/components/SideBar/index.tsx
  src/components/modal/CreateDashboard/CreateDashboard.module.scss
  src/components/modal/CreateDashboard/index.tsx
  src/components/modal/ModalPortal.tsx
Labels: 📄pages

#57 대시보드 수정 페이지 mock데이터 -> 실제데이터
  src/app/dashboard/[boardId]/edit/editComponents/DashboardChange.tsx
  src/app/dashboard/[boardId]/edit/editComponents/InviteStatus.tsx
  src/app/dashboard/[boardId]/edit/editComponents/MemberManagement.tsx
  src/app/dashboard/[boardId]/edit/page.tsx
  src/components/modal/modalInvite/ModalInvite.tsx
Labels: 📄pages

#61 feature: Landing 페이지 작업(#54)
  public/images/landing/bottom1.png
  public/images/landing/bottom2.png
  public/images/landing/bottom3.png
  public/images/landing/middle1.png
  public/images/landing/middle2.png
  public/images/landing/top1.png
  src/app/page.module.scss
  src/app/page.tsx
  src/components/common/Footer/Footer.module.scss
  src/components/common/Footer/index.tsx
Labels: 📄pages

#63 Feature/dashobard boardid
  src/app/dashboard/[boardId]/page.tsx
  src/components/Card/Card.tsx
  src/components/Column/index.tsx
  src/components/modal/ChangeColumn/ChangeColumn.module.scss
  src/components/modal/ChangeColumn/index.tsx
  src/components/modal/CreateColumn/CreateColumn.module.scss
  src/components/modal/CreateColumn/index.tsx
  src/components/modal/DeleteTask/index.tsx
  src/components/modal/ModalPortal.tsx
  src/components/modal/Task/Comment/Comments.tsx
  src/components/modal/Task/index.tsx
  src/components/modal/index.tsx
  src/components/modal/modalExample/ExampleModal.tsx
  src/components/modal/modalInput/ModalInput.module.scss
  src/components/modal/modalInput/NameInput/NameInput.module.scss
  src/components/modal/modalInput/NameInput/index.tsx
  src/hooks/useFetchToken.ts
  src/types/DashboardTypes.ts
Labels: ✨component, 📄pages, 🪝hook

#68 feature: mydashboard, sidebar pagination(#32)
  src/app/dashboard/[boardId]/edit/editComponents/MemberManagement.tsx
  src/app/mydashboard/page.tsx
  src/components/InvitedBoard/InviteList/index.tsx
  src/components/InvitedBoard/InviteList/inviteList.module.scss
  src/components/InvitedBoard/InviteListItem/index.tsx
  src/components/InvitedBoard/InvitedBoardSearchForm/index.tsx
  src/components/InvitedBoard/index.tsx
  src/components/Modal/ModalInput/NameInput/index.tsx
  src/components/Modal/Task/Comment/Comments.tsx
  src/components/Modal/Task/Kebob/KebobMenu.tsx
  src/components/MyDashboardList/index.tsx
  src/components/SideBar/index.tsx
  src/components/common/Header/DashBoardHeader/index.tsx
  src/contexts/inviteContext.tsx
  src/hooks/useFetchToken.ts
Labels: ✨component, 📄pages

#65 feature: 할일 생성/추가 모달 ui
  src/components/Modal/ModalButton/SubmitButton/index.tsx
  src/components/Modal/ModalDropDown/MemberDropDown/index.tsx
  src/components/Modal/ModalInput/DeadlineInput/DeadlineInput.module.scss
  src/components/Modal/ModalInput/NameInput/index.tsx
  src/components/Modal/ModalInput/TagInput/TagInput.module.scss
  src/components/Modal/Task/Comment/Comments.tsx
  src/components/Modal/index.tsx
  src/components/common/FileInput/FileInput.module.scss
  src/components/common/Header/DashBoardHeader/DashBoardHeader.module.scss
  src/components/common/Header/DashBoardHeader/EachDashBoardHeade/index.tsx
  src/components/common/Header/LandingPageHeader/LandingPageHeader.module.scss
  src/components/common/Input/Input.module.scss
  src/components/modal/CreateTask/CreateTask.module.scss
  src/components/modal/CreateTask/index.tsx
  src/components/modal/ModifyTask/ModifyTask.module.scss
  src/components/modal/ModifyTask/index.tsx
Labels: ✨component

#66 fix: 헤더 수정 및 프로필 클릭시 마이페이지 이동
  src/components/Modal/ModalInput/NameInput/index.tsx
  src/components/common/Header/DashBoardHeader/DashBoardHeader.module.scss
  src/components/common/Header/DashBoardHeader/EachDashBoardHeade/EachDashBoardHeader.module.scss
  src/components/common/Header/DashBoardHeader/EachDashBoardHeade/index.tsx
  src/components/common/Header/DashBoardHeader/index.tsx
Labels: 🐛fix, ✨component

#67 feat: 마이페이지 로그아웃 버튼
  src/app/mypage/MyPage.module.scss
  src/app/mypage/page.tsx
Labels: 📄pages

#70 fix: import 경로 수정
  .eslintrc.json
  src/app/dashboard/[boardId]/edit/editComponents/DashboardChange.tsx
  src/app/dashboard/[boardId]/page.tsx
  src/app/login/page.tsx
  src/app/mypage/page.tsx
  src/components/Column/index.tsx
  src/components/Modal/ModalInput/NameInput/index.tsx
  src/components/Modal/Task/Comment/Comments.tsx
  src/components/Modal/Task/Kebob/KebobMenu.tsx
  src/components/SideBar/index.tsx
  src/components/common/FileInput/index.tsx
  src/components/common/Header/DashBoardHeader/EachDashBoardHeade/index.tsx
  src/components/common/Header/DashBoardHeader/index.tsx
  src/components/common/Header/LandingPageHeader/index.tsx
  src/components/common/Input/index.tsx
Labels: 🐛fix

#71 Feat : 대시보드 수정 페이지 ( context, 반응형, 짜잘한 기능 구현)
  .eslintrc.json
  src/app/NotFound.module.scss
  src/app/dashboard/[boardId]/Dashboard.module.scss
  src/app/dashboard/[boardId]/edit/BoardEdit.module.scss
  src/app/dashboard/[boardId]/edit/editComponents/DashboardChange.module.scss
  src/app/dashboard/[boardId]/edit/editComponents/DashboardChange.tsx
  src/app/dashboard/[boardId]/edit/editComponents/InviteStatus.module.scss
  src/app/dashboard/[boardId]/edit/editComponents/InviteStatus.tsx
  src/app/dashboard/[boardId]/edit/editComponents/MemberManagement.module.scss
  src/app/dashboard/[boardId]/edit/editComponents/MemberManagement.tsx
  src/app/dashboard/[boardId]/edit/editComponents/PreviousPageButton.module.scss
  src/app/dashboard/[boardId]/edit/page.tsx
  src/app/dashboard/[boardId]/page.tsx
  src/app/login/page.tsx
  src/app/not-found.tsx
  src/app/signup/page.tsx
  src/components/Column/index.tsx
  src/components/InvitedBoard/InviteList/inviteList.module.scss
  src/components/InvitedBoard/InviteListItem/index.tsx
  src/components/InvitedBoard/InvitedBoard.module.scss
  src/components/Modal/CreateDashboard/index.tsx
  src/components/Modal/ModalDropDown/MemberDropDown/index.tsx
  src/components/Modal/ModalInvite/ModalInvite.module.scss
  src/components/Modal/ModalInvite/index.tsx
  src/components/Modal/Task/Comment/Comments.tsx
  src/components/Modal/Task/Kebob/KebobMenu.tsx
  src/components/Modal/Task/index.tsx
  src/components/MyDashboardList/index.tsx
  src/components/SideBar/index.tsx
  src/components/common/Button/PaginationButton/PaginationButton.module.scss
  src/components/common/Header/DashBoardHeader/EachDashBoardHeade/index.tsx
  src/components/common/Header/DashBoardHeader/index.tsx
  src/components/modal/CreateTask/index.tsx
  src/components/modal/ModifyTask/index.tsx
  src/constants/ApiUrl.ts
  src/contexts/idContext.tsx
  src/contexts/inviteContext.tsx
Labels: 🐛fix, ✨component, 📄pages

#72 feat: confirm modal 추가, 디자인수정
  next.config.mjs
  src/app/dashboard/[boardId]/Dashboard.module.scss
  src/components/Card/Card.module.scss
  src/components/Card/Card.tsx
  src/components/Card/mock.json
  src/components/Column/Column.module.scss
  src/components/Column/index.tsx
  src/components/Column/mock.json
  src/components/Modal/ChangeColumn/ChangeColumn.module.scss
  src/components/Modal/ChangeColumn/index.tsx
  src/components/Modal/ConfirmModal/ConfirmModal.module.scss
  src/components/Modal/ConfirmModal/index.tsx
  src/components/Modal/ModalInput/CommentInput/CommentInput.module.scss
  src/components/Modal/ModalInput/CommentInput/index.tsx
  src/components/Modal/Task/Comment/Comments.module.scss
  src/components/Modal/Task/Comment/Comments.tsx
  src/components/Modal/Task/Kebob/KebobMenu.tsx
  src/components/Modal/Task/Task.module.scss
  src/components/Modal/Task/index.tsx
  src/components/common/Profile/Profile.module.scss
  src/components/common/Profile/index.tsx
  src/hooks/useFormattedDate.ts
Labels: ✨component

#76 feat: header, createTaskModal, mypage 데이터 fetch
  src/app/mypage/page.tsx
  src/components/Modal/CreateTask/CreateTask.module.scss
  src/components/Modal/CreateTask/index.tsx
  src/components/Modal/ModalButton/SubmitButton/index.tsx
  src/components/Modal/ModalInput/AssigneeInput/AssigneeInput.module.scss
  src/components/Modal/ModalInput/AssigneeInput/index.tsx
  src/components/Modal/ModalInput/DeadlineInput/index.tsx
  src/components/Modal/ModalInput/TagInput/index.tsx
  src/components/Modal/ModalInput/index.tsx
  src/components/Modal/ModifyTask/ModifyTask.module.scss
  src/components/Modal/ModifyTask/index.tsx
  src/components/common/Button/BasicSubmitButton/index.tsx
  src/components/common/Chip/NumberChip.tsx
  src/components/common/FileInput/index.tsx
  src/components/common/Header/DashBoardHeader/EachDashBoardHeade/index.tsx
  src/components/common/Header/DashBoardHeader/EachDashBoardHeader/EachDashBoardHeader.module.scss
  src/components/common/Header/DashBoardHeader/EachDashBoardHeader/index.tsx
  src/components/common/Header/DashBoardHeader/index.tsx
  src/components/modal/CreateTask/index.tsx
  src/components/modal/ModifyTask/index.tsx
Labels: 🐛fix, ✨component, 📄pages

#74 feature: Alert Toast 추가(#62)
  package-lock.json
  package.json
  src/app/layout.tsx
  src/app/login/page.tsx
  src/app/mypage/page.tsx
  src/app/signup/page.tsx
  src/constants/ApiUrl.ts
  src/hooks/useFetchToken.ts
  src/util/Toast.ts
Labels: ♻️refactor

#80 fix: 랜딩페이지 스타일 수정
  src/app/(home)/page.module.scss
Labels: 🐛fix

#86 feature: dashboardlist context 생성 및 적용
  src/app/(dashboard)/layout.tsx
  src/components/InvitedBoard/InviteListItem/index.tsx
  src/components/Modal/CreateDashboard/index.tsx
  src/components/MyDashboardList/index.tsx
  src/components/SideBar/SideBarListItem/index.tsx
  src/components/SideBar/index.tsx
  src/components/common/Button/DashboardButton/index.tsx
  src/contexts/dashboardContext.tsx
  src/contexts/inviteContext.tsx
Labels: 📄pages

#87 feature: 주소 경로에 따른 header 노출 기능, 폰트 설정 추가
  package-lock.json
  package.json
  src/app/(dashboard)/dashboard/[boardId]/edit/editComponents/InviteStatus.tsx
  src/app/(dashboard)/dashboard/[boardId]/edit/editComponents/MemberManagement.tsx
  src/app/(dashboard)/layout.tsx
  src/app/layout.tsx
  src/components/Modal/ModalInvite/index.tsx
  src/components/SideBar/index.tsx
  src/components/common/Header/DashBoardHeader/EachDashBoardHeader/index.tsx
  src/styles/_reset.scss
  src/styles/globals.scss
Labels: ✨component

#85 Fix/dashboard boardid
  package-lock.json
  package.json
  src/app/(dashboard)/dashboard/[boardId]/Dashboard.module.scss
  src/app/(dashboard)/dashboard/[boardId]/page.tsx
  src/components/Column/Column.module.scss
  src/components/Column/index.tsx
  src/components/Modal/ChangeColumn/index.tsx
  src/components/Modal/CreateColumn/index.tsx
  src/components/Modal/ModalButton/SubmitButton/index.tsx
  src/components/Modal/Task/Comment/Comments.tsx
  src/components/Modal/Task/index.tsx
Labels: 🐛fix, 📄pages

#82 Feature/editdashboard
  src/app/(dashboard)/dashboard/[boardId]/edit/BoardEdit.module.scss
  src/app/(dashboard)/dashboard/[boardId]/edit/editComponents/DashboardChange.tsx
  src/app/(dashboard)/dashboard/[boardId]/edit/editComponents/InviteStatus.module.scss
  src/app/(dashboard)/dashboard/[boardId]/edit/editComponents/InviteStatus.tsx
  src/app/(dashboard)/dashboard/[boardId]/edit/editComponents/MemberManagement.module.scss
  src/app/(dashboard)/dashboard/[boardId]/edit/editComponents/MemberManagement.tsx
  src/app/(dashboard)/dashboard/[boardId]/edit/page.tsx
  src/app/(home)/signup/page.tsx
  src/components/Modal/ModalInvite/index.tsx
Labels: 🐛fix, ✨component, 📄pages

#91 Fix/dashboard design
  src/app/(dashboard)/dashboard/[boardId]/edit/editComponents/DashboardChange.tsx
  src/components/Card/Card.module.scss
  src/components/Modal/CreateDashboard/index.tsx
  src/components/Modal/Task/Comment/Comments.module.scss
  src/components/Modal/Task/Comment/Comments.tsx
  src/components/common/Chip/ColorChip.module.scss
  src/components/common/Chip/ColorChip.tsx
Labels: 🐛fix, ✨component

#92 fix: dashboardId Number 로 수정
  src/app/(dashboard)/dashboard/[boardId]/page.tsx
  src/app/(dashboard)/mypage/page.tsx
  src/components/Modal/CreateTask/index.tsx
Labels: 🐛fix, ✨component

#95 fix: 모달 이미지 첨부 및 스크롤 변경
  src/app/(dashboard)/mypage/page.tsx
  src/components/Modal/CreateTask/CreateTask.module.scss
  src/components/Modal/ModalInput/DeadlineInput/DeadlineInput.module.scss
  src/components/Modal/ModifyTask/ModifyTask.module.scss
  src/components/Modal/ModifyTask/index.tsx
  src/components/Modal/Task/index.tsx
  src/components/common/FileInput/index.tsx
Labels: 🐛fix

#93 fix: import 에러 수정
  src/app/(dashboard)/dashboard/[boardId]/page.tsx
  src/components/Column/index.tsx
  src/components/Modal/CreateTask/index.tsx
  src/components/Modal/ModalInput/AssigneeInput/index.tsx
  src/components/Modal/ModalInput/DeadlineInput/index.tsx
  src/components/Modal/ModalInput/StateInput/index.tsx
  src/components/Modal/ModalInput/TagInput/index.tsx
  src/components/Modal/ModalPortal.tsx
  src/components/Modal/ModifyTask/index.tsx
  src/components/common/FileInput/index.tsx
  src/components/common/Header/DashBoardHeader/EachDashBoardHeader/index.tsx
Labels: 🐛fix

#97 fix: 개별대시보드 헤더 프로필 수정, 마이페이지 input 디자인 수정
  src/app/(dashboard)/mypage/MyPage.module.scss
  src/app/(dashboard)/mypage/page.tsx
  src/components/common/Header/DashBoardHeader/EachDashBoardHeader/index.tsx
  src/components/common/Input/Input.module.scss
  src/components/common/Input/index.tsx
Labels: 🐛fix

#94 fix: button props 수정, 잘못 사용된 부분 컴포넌트 교체
  src/components/Modal/CreateTask/index.tsx
  src/components/Modal/ModalButton/Button/ModalButton.module.scss
  src/components/Modal/ModalButton/Button/index.tsx
  src/components/Modal/ModalButton/SubmitButton/index.tsx
  src/components/Modal/ModifyTask/index.tsx
  src/components/common/Button/BasicSubmitButton/index.tsx
  src/components/common/Button/Button/Button.module.scss
Labels: 🐛fix

#100 feat: 수정 모달 연결
  src/components/Card/Card.tsx
  src/components/Column/index.tsx
  src/components/Modal/CreateTask/CreateTask.module.scss
  src/components/Modal/ModalInput/AssigneeInput/AssigneeInput.module.scss
  src/components/Modal/ModalInput/AssigneeInput/index.tsx
  src/components/Modal/ModalInput/StateInput/StateInput.module.scss
  src/components/Modal/ModalInput/StateInput/index.tsx
  src/components/Modal/ModifyTask/ModifyTask.module.scss
  src/components/Modal/ModifyTask/index.tsx
  src/components/Modal/Task/Kebob/KebobMenu.tsx
  src/components/Modal/Task/index.tsx
Labels: 🐛fix

#105 Fix/dashboard pages
  src/app/(dashboard)/layout.tsx
  src/components/Column/index.tsx
  src/components/Modal/ChangeColumn/ChangeColumn.module.scss
  src/components/Modal/ChangeColumn/index.tsx
  src/components/Modal/ModalButton/Button/ModalButton.module.scss
  src/components/Modal/ModalButton/SubmitButton/ModalSubmitButton.module.scss
  src/components/Modal/ModalInput/CommentInput/CommentInput.module.scss
  src/components/Modal/ModalInput/CommentInput/index.tsx
  src/components/Modal/Task/Comment/Comments.module.scss
  src/components/Modal/Task/Comment/Comments.tsx
  src/components/Modal/Task/Task.module.scss
  src/components/Modal/Task/index.tsx
  src/components/common/Header/DashBoardHeader/EachDashBoardHeader/index.tsx
  src/contexts/userContext.tsx
Labels: 🐛fix

#107 Fix: 로그인&회원가입 유효성 검사 및 반응형 적용
  src/app/(home)/login/Login.module.scss
  src/app/(home)/login/page.tsx
  src/app/(home)/signup/Signup.module.scss
  src/app/(home)/signup/page.tsx
  src/components/common/Input/Input.module.scss
Labels: 🐛fix

#106 feat, fix: 마이페이지 비밀번호 눈 모양 이미지 추가, 할일 생성/추가 모달 오류 수정
  src/app/(dashboard)/mypage/MyPage.module.scss
  src/app/(dashboard)/mypage/page.tsx
  src/components/Modal/CreateTask/CreateTask.module.scss
  src/components/Modal/CreateTask/index.tsx
  src/components/Modal/LogoutModal/LogoutModal.module.scss
  src/components/Modal/ModalInput/AssigneeInput/AssigneeInput.module.scss
  src/components/Modal/ModalInput/AssigneeInput/index.tsx
  src/components/Modal/ModalInput/StateInput/StateInput.module.scss
  src/components/Modal/ModalInput/StateInput/index.tsx
  src/components/Modal/ModifyTask/ModifyTask.module.scss
  src/components/Modal/ModifyTask/index.tsx
  src/components/common/FileInput/FileInput.module.scss
  src/components/common/FileInput/index.tsx
Labels: 🐛fix

#109 fix: 모달 디자인 수정
  src/components/Modal/CreateTask/CreateTask.module.scss
  src/components/Modal/ModalInput/DeadlineInput/DeadlineInput.module.scss
  src/components/Modal/ModifyTask/ModifyTask.module.scss
  src/components/Modal/ModifyTask/index.tsx
Labels: 🐛fix

#110 fix: 모달 디자인 수정, 마이페이지 새로고침 반영, 개별대시보드 헤더 프로필 안나오던 문제 해결
  src/app/(dashboard)/mypage/page.tsx
  src/components/Modal/CreateTask/CreateTask.module.scss
  src/components/Modal/CreateTask/index.tsx
  src/components/Modal/ModalInput/AssigneeInput/AssigneeInput.module.scss
  src/components/Modal/ModalInput/AssigneeInput/index.tsx
  src/components/Modal/ModalInput/StateInput/StateInput.module.scss
  src/components/Modal/ModalInput/StateInput/index.tsx
  src/components/Modal/ModifyTask/ModifyTask.module.scss
  src/components/Modal/ModifyTask/index.tsx
  src/components/common/Header/DashBoardHeader/EachDashBoardHeader/index.tsx
Labels: 🐛fix

#114 fix: 담당자모달 / 상태 input 디자인 수정
  src/components/Modal/ModalInput/AssigneeInput/AssigneeInput.module.scss
  src/components/Modal/ModalInput/StateInput/StateInput.module.scss
Labels: 🐛fix

#108 Fix/dashboard design
  src/app/(dashboard)/layout.tsx
  src/app/(home)/layout.tsx
  src/app/(home)/login/page.tsx
  src/components/Card/Card.tsx
  src/components/Column/Column.module.scss
  src/components/Column/index.tsx
  src/components/Modal/ChangeColumn/index.tsx
  src/components/Modal/CreateColumn/index.tsx
  src/components/Modal/ModalInput/CommentInput/CommentInput.module.scss
  src/components/Modal/ModalInput/NameInput/index.tsx
  src/components/Modal/ModalInput/index.tsx
  src/components/Modal/ModifyTask/index.tsx
  src/components/Modal/Task/Comment/Comments.module.scss
  src/components/Modal/Task/Comment/Comments.tsx
  src/components/Modal/Task/Task.module.scss
  src/components/Modal/Task/index.tsx
  src/components/common/Header/DashBoardHeader/EachDashBoardHeader/index.tsx
  src/contexts/userContext.tsx
  src/types/DashboardTypes.ts
Labels: 🐛fix

#115 fix: 모바일 이미지 없을 경우 수정
  src/components/Modal/Task/Task.module.scss
  src/components/Modal/Task/index.tsx
Labels: 🐛fix

#117 fix: 할일 생성/수정 모달 세로 수정
  src/components/Modal/CreateTask/CreateTask.module.scss
  src/components/Modal/ModifyTask/ModifyTask.module.scss
Labels: 🐛fix
